# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reload_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(default='', max_length=100)),
                ('Country_short_name', models.CharField(blank=True, default='', max_length=100)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
