# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reload_country',
            options={'verbose_name': 'Reload Country'},
        ),
    ]
