# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0002_auto_20180102_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reload_country',
            options={'verbose_name': 'Reload Country', 'verbose_name_plural': 'Reload Country'},
        ),
    ]
