# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0005_phone_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='dtgfsghr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sohel_fls', models.ManyToManyField(blank=True, to='topup_projects.Reload_country')),
            ],
        ),
    ]
