# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0007_dtgfsghr_sifat_fls'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='products',
            field=models.ManyToManyField(blank=True, to='topup_projects.Product'),
        ),
        migrations.AddField(
            model_name='reload_country',
            name='operators',
            field=models.ManyToManyField(blank=True, to='topup_projects.Operator'),
        ),
    ]
