# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0008_auto_20180107_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtgfsghr',
            name='sifat_fls',
        ),
        migrations.RemoveField(
            model_name='dtgfsghr',
            name='sohel_fls',
        ),
        migrations.DeleteModel(
            name='dtgfsghr',
        ),
    ]
