# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0010_auto_20180111_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topup',
            options={'verbose_name': 'topup', 'verbose_name_plural': 'topup'},
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 11, 16, 12, 51, 685000)),
        ),
    ]
