# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0012_auto_20180112_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='', max_length=120)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 12, 58, 36, 289000)),
        ),
    ]
