# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0014_auto_20180114_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Change_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 13, 4, 40, 366000)),
        ),
    ]
