# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0015_auto_20180114_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 13, 6, 10, 427000)),
        ),
    ]
