# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0016_auto_20180114_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Change_password',
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 13, 21, 1, 499000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
