# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0017_auto_20180114_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User',
        ),
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 13, 26, 49, 232000)),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
