# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0020_auto_20180114_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 13, 45, 4, 109000)),
        ),
    ]
