# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0025_auto_20180114_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 15, 12, 1, 31, 369000)),
        ),
    ]
