# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0026_auto_20180115_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 16, 13, 31, 52, 34000)),
        ),
    ]
