# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup_projects', '0028_auto_20180116_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 18, 11, 0, 55, 904000)),
        ),
    ]
